version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@db/postgres
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
