development:
  metadata_adapter: <%= ENV['VALKYRIE_METADATA'] || 'postgres' %>
  storage_adapter: <%= ENV['VALKYRIE_STORAGE'] || 'postgres' %>

test:
  metadata_adapter: <%= ENV['VALKYRIE_METADATA'] || 'memory' %>
  storage_adapter: <%= ENV['VALKYRIE_STORAGE'] || 'memory' %>

production:
  metadata_adapter: <%= ENV['VALKYRIE_METADATA'] || 'postgres' %>
  storage_adapter: <%= ENV['VALKYRIE_STORAGE'] || 'postgres' %>
